duckdb/duckdb-delta

CMakeLists.txt
With PR https://github.com/duckdb/duckdb_delta/pull/13 S3 stopped working. Somehow the cloud feature was not properly enabled. Switching to `--workspace` seems to have fixed it.
=> restore s3 functionality

src/functions/delta_scan.cpp
fixes https://github.com/duckdb/duckdb_delta/issues/17
=> Fix Path issues related to trailing slashes

src/include/delta_utils.hpp, test/sql/dat/nested_types.test, test/sql/dat/primitive_types.test
=> add missing nested types

CMakeLists.txt, src/delta_utils.cpp, src/functions/delta_scan.cpp, src/include/delta_utils.hpp, src/include/functions/delta_scan.hpp, test/sql/generated/tpcds.test_slow
Kernel pointers were not properly freed. 
Fixed by wrapping everything kernel in the UniqueKernelPointers. Refactored the utils a little in the process
=> Fix "too many open files"

src/functions/delta_scan.cpp
This was fun :). This fixes https://github.com/delta-incubator/delta-kernel-rs/issues/233
Basically, if you push down a predicate, you can have a situation where a batch of files that does include an `Add` file, doesn't actually return any files to scan, because they are all filtered out. The kernel can't know this for sure because we don't introspect the data until the engine asks us to extract it for them. So in the case of running:
```SQL
SELECT letter, number
FROM delta_scan('${DAT_PATH}/out/reader_tests/generated/basic_append/delta')
WHERE number < 2
```
the first batch included one file, but it's filtered out by the predicate, so nothing actually came out and `resolved_files.size() == size_before` would be true, so `duckdb` would just stop looking for more files. But there _is_ one …
=> Shouldn't stop just because a step returned no files

CMakeLists.txt, Makefile, scripts/generate_test_data.py, src/delta_utils.cpp, src/functions/delta_scan.cpp, src/include/delta_utils.hpp, test/sql/dat/basic_append.test, test/sql/generated/file_skipping_all_types.test
now supporting filter pushdown for more types. 
Applies fix from https://github.com/duckdb/duckdb_delta/pull/31 (which fails CI as is) 
Code is from unmerged kernel commit https://github.com/delta-incubator/delta-kernel-rs/pull/258, will switch back to kernel main branch once that is merged.
added `test/sql/generated/file_skipping_all_types.test` but it doesn't appear to succesfully skip files yet.
=> Bump delta extension

.github/workflows/LocalTesting.yml, extension_config.cmake, scripts/create_minio_credential_file.sh, scripts/upload_test_files_to_minio.sh, src/functions/delta_scan.cpp, test/sql/cloud/minio_local/gcs_r2.test, test/sql/cloud/minio_local/minio_local.test, vcpkg.json
Fixes https://github.com/duckdb/duckdb_delta/issues/41, https://github.com/duckdb/duckdb_delta/issues/45 and https://github.com/duckdb/duckdb_delta/issues/14
Now minio and thereby any custom S3 endpoint should be supported, I've also added support for R2 and GCS urls which are rewritted to s3 urls when passed to the kernel.
Also I added a CI job that tests stuff against a local minio instance
=> add support for minio, r2, gcs

src/functions/delta_scan.cpp, test/sql/dat/all.test
fixes https://github.com/duckdb/duckdb_delta/issues/51
=> fix bug with count star and partition values

CMakeLists.txt, src/functions/delta_scan.cpp, src/include/delta_kernel_ffi.hpp, src/include/delta_utils.hpp, src/include/functions/delta_scan.hpp, test/sql/dat/all.test
Bump kernel to v0.2.0: all DAT tables are now correctly read
=> bump kernel to v0.2.0

README.md
I've tidied up the README a bit according to my local markdown linter configuration. I could configure this job as a Github action if wanted?
I also added a bit of documentation about configuring an Azure secret, as per https://github.com/duckdb/duckdb_delta/issues/64.
=> chore: tidy up README and make cloud documentation more agnostic

src/functions/delta_scan.cpp
fixes https://github.com/duckdb/duckdb_delta/issues/85
=> handle when kernel returns a nullptr for the stats

src/functions/delta_scan.cpp
fixes #43 by removing the need to include the endoint in the secret.
Missing tests :(
=> fix: correct endpoint when using onelake

CMakeLists.txt, src/include/delta_kernel_ffi.hpp
=> bump kernel to v0.4.0

src/functions/delta_scan.cpp
In case of duckdb-wasm (potentially also in other configurations) parquet might not be already loaded.
This makes so that in those cases error change from:
```sql
LOAD delta;
```
```
Invalid Input Error: Initialization function "delta_init" from file "/Users/carlo/.duckdb/extensions/v1.1.3/osx_arm64/delta.duckdb_extension" threw an exception: "Function with name "parquet_scan" not found in ExtensionUtil::GetTableFunction"
```
to either successfully autoinstalling or autoloading parquet OR informing that there has been an autoloading problem with the `parquet` extension.
This is minor, and should not change any currently tested code-path.
=> autoload('parquet') since it's needed for scan_parquet

.clang-format, .github/workflows/MainDistributionPipeline.yml, CMakeLists.txt, src/delta_extension.cpp, src/delta_functions.cpp, src/delta_utils.cpp, src/functions/delta_scan.cpp, src/functions/expression_functions.cpp, src/include/delta_functions.hpp, src/include/delta_kernel_ffi.hpp, src/include/delta_utils.hpp, src/include/functions/delta_scan.hpp, src/include/storage/delta_catalog.hpp, src/include/storage/delta_schema_entry.hpp, src/include/storage/delta_table_entry.hpp, src/include/storage/delta_transaction.hpp, src/storage/delta_catalog.cpp, src/storage/delta_schema_entry.cpp, src/storage/delta_table_entry.cpp, src/storage/delta_transaction.cpp
Since formatting was changed in main, merging now avoids painful merge conflicts before adding more code to feature
=> Main into feature

scripts/generate_test_data.py, src/delta_extension.cpp, src/functions/delta_scan.cpp, test/sql/generated/file_skipping_all_types.test
This allows easier debugging of performance issues since we can now communicate how many files are skipped by the delta kernel. This also helps when writing tests, which I did update now that I can actually test that file skipping is done correctly
The feature is enabled with a new option `delta_scan_explain_files_filtered` which is **ON** by default. The feature is really useful and I feel it outweighs the risk of people getting tripped up by a slightly different timing of the delta scan operator when running with `explain analyze`.
```
EXPLAIN ANALYZE SELECT value1, value2, value3
FROM delta_scan('./data/generated/test_file_skipping/int/delta_lake')
WHERE
value1 > 1 and
value2 > 2 and
value3 < 4
```
wil now print:
```
┌───────────────────────────┐
│           QUERY           │ …
```
=> Add total files filtered

.github/workflows/LocalTesting.yml, Makefile, src/functions/delta_scan.cpp, src/include/functions/delta_scan.hpp, src/storage/delta_catalog.cpp, test/sql/generated/attach_parallel.test
Fix problems with thread safety with DeltaSnapshot, add tests for this. 
Running CI with sanitizers for this is stil problematic and remains TODO; we are running out of both disk space and memory when building delta in debug mode.
=> Thread safety

.github/workflows/MainDistributionPipeline.yml, Makefile, src/delta_extension.cpp, src/delta_utils.cpp, src/include/delta_utils.hpp, src/storage/delta_catalog.cpp, test/sql/delta_kernel_rs/logging.test
With DuckDB's new logging infra, we can hook up the delta logging to the DuckDB logger to allow us to expose the kernel logging in a clean way to DuckDB users.
To enable:
```SQL
set enable_logging=true;
set delta_kernel_logging=true;
set logging_level='DEBUG'
FROM delta_scan('...');
FROM duckdb_logs;
```
will now show entries such as:
```
2025-01-13 12:30:22.033	delta.Kernel	DEBUG	[delta_kernel_ffi] ffi/src/lib.rs@363 : dropping engine interface 	DATABASE	NULL	NULL	NULL
2025-01-13 12:30:22.033	delta.Kernel	DEBUG	[delta_kernel_ffi] ffi/src/lib.rs@594 : engine released snapshot 	DATABASE	NULL	NULL	NULL
```
Note that the 'delta_kernel_logging' setting was added to explicitly enable kernel log forwarding, because enabling them by default might be potentially expensive even if DuckDB logging …
=> Add Logging

src/functions/delta_scan.cpp, src/include/functions/delta_scan.hpp
Adds a workaround for #150 by assuming there are no deletion vectors when we run into the error message `Deletion Vector error: Unknown storage format: ''.` when trying to fetch it.
This works on the assumption that this error will get triggered due to https://github.com/delta-io/delta-kernel-rs/issues/669 when we try to scan a table with checkpoint files without a deletion vector.
This workaround is to be removed after the aforementioned delta-kernel-rs issue is fixed
=> Add workaround for 150

src/delta_extension.cpp, src/functions/delta_scan/delta_multi_file_list.cpp, src/functions/delta_scan/delta_multi_file_reader.cpp, src/functions/delta_scan/delta_scan.cpp, src/include/functions/delta_scan/delta_multi_file_list.hpp, src/include/functions/delta_scan/delta_scan.hpp, src/include/storage/delta_catalog.hpp, src/storage/delta_catalog.cpp, src/storage/delta_table_entry.cpp, test/sql/dat/custom_parameters.test, test/sql/generated/file_skipping_dynamic.test, test/sql/generated/file_skipping_params.test, test/sql/generated/partitioned_large.test
In https://github.com/duckdb/duckdb-delta/pull/147 we introduced partition info pushdown and filter pushdown. 
However, after some more testing I realize that this PR introduced performance regressions on high latency filesystems. The reason is that these changes were introducing a lot of unnecessary delta metadata (re)scanning.
This PR adds configuration settings to enable and disable both filter pushdown and partition info pushdown:
For filter pushdown we can now do 
```SQL
-- default (all)
SELECT * FROM delta_scan('...', pushdown_filters='all') 
-- alternative settings
SELECT * FROM delta_scan('...', pushdown_filters='none')
SELECT * FROM delta_scan('...', pushdown_filters='constant_only')
SELECT * FROM delta_scan('...', pushdown_filters='dynamic_only')
-- also works with attach
ATTACH …
```
=> Make partition info pushdown and filter pushdown optional

CMakeLists.txt, src/delta_utils.cpp, src/functions/delta_scan/delta_multi_file_list.cpp, src/functions/delta_scan/delta_multi_file_reader.cpp, src/include/delta_kernel_ffi.hpp, src/include/delta_utils.hpp, src/include/functions/delta_scan/delta_multi_file_list.hpp, test/sql/main/test_expression.test
This PR switches the way we get partition values from kernel. Before we would use the partition map to do this. After this PR we switch to parsing the transform expression.
In the process we bump kernel to v0.8.0
=> Switch to parsing transforms for partition values

src/delta_utils.cpp, src/functions/delta_scan/delta_multi_file_list.cpp, src/include/delta_utils.hpp, src/include/functions/delta_scan/delta_multi_file_list.hpp, test/sql/main/test_error_messages.test
fixes https://github.com/duckdb/duckdb-delta/issues/29
Avoids throwing in visitor callbacks because that crashes in ugly ways. Reworks the API to make it harder to accidentally do that.
=> cleanup kernel error handling

CMakeLists.txt, src/delta_extension.cpp, src/delta_log_types.cpp, src/delta_macros.cpp, src/delta_utils.cpp, src/include/delta_log_types.hpp, test/sql/delta_kernel_rs/logging.test, test/sql/generated/file_skipping_dynamic.test, test/sql/generated/file_skipping_params.test
Bumps to latest duckdb, applies changes to logging API by switching the kernel logging to structured logging.
I've left the filter pushdown logging as is, we can look into making a generalized version of that which iceberg can benefit from too later
=> Bump duckdb

src/functions/delta_scan/delta_multi_file_list.cpp
There is undefined behavior in the `DeltaMultiFileList::InitializeScan` function.
[`scan_table_root`](https://github.com/delta-io/delta-kernel-rs/blob/bbca6261fbfe6d9aaf9bc3f6ad219b8279b76a7a/ffi/src/scan.rs#L126) returns the pointer allocated by `allocate_fn`, and in the case of `InitializeScan`, it is using `new`.
https://github.com/duckdb/duckdb-delta/blob/4bd160a5ac4a4168bc27aace49ede0a3cdc7ad5b/src/functions/delta_scan/delta_multi_file_list.cpp#L688
Therefore, `ptr` must be deallocated using `delete` instead of `free`.
---
This fixes the following error when running the _basic_append.test_ SQLLogic test:
> pointer being freed was not allocated
=> Use `delete` for pointer allocated with `new`

.github/workflows/MainDistributionPipeline.yml
Workaround to fix uploads to our r2 based cache, see https://github.com/duckdb/extension-ci-tools/pull/212
=> Set `downgrade_aws_cli` option to enable uploading to vcpkg cache

src/storage/delta_transaction.cpp, test/sql/generated/writing/append/test_arrow_release.test
This PR uses the logger combined with a simple write test to confirm that arrow data passed to kernel is actually freed by kernel
=> Add tests for arrow being freed properly by kernel
